language: node_js
cache: yarn
node_js:
  - "6"
  - "node"
notifications:
  email: false
install:
  - yarn
  - yarn global add codecov
script:
  - yarn run lint
  - yarn test
after_success:
  - codecov
